services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CHALLENGE_DIFFICULTY=0000
    networks:
      - pow-network

  client:
    build:
      context: client
      dockerfile: Dockerfile
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8080
      - REQUESTS_DELAY_MS=100
    networks:
      - pow-network

networks:
  pow-network:
    driver: bridge 