services:
  server:
    build:
      context: .
      dockerfile: server.Dockerfile
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - CHALLENGE_DIFFICULTY=2
      - SERVER_MODE=quotes
      - PROXY_TARGET=http://example.com
    networks:
      - pow-network

  client:
    build:
      context: .
      dockerfile: client.Dockerfile
    depends_on:
      - server
    environment:
      - SERVER_HOST=server
      - SERVER_PORT=8080
      - REQUEST_DELAY=100ms
    networks:
      - pow-network

networks:
  pow-network:
    driver: bridge 