client:
  server_host: "${SERVER_HOST}"  # host to bind to
  server_port: "${SERVER_PORT}"     # port to listen on
  request_delay: "${REQUEST_DELAY}" # requests delay
  connection:
    read_timeout: "30s"   # read timeout
    write_timeout: "30s"  # write timeout

    
