client:
  server_host: "0.0.0.0"  # host to bind to
  server_port: "8080"     # port to listen on
  rps: 10                 # requests per second
  connection:
    read_timeout: "30s"   # read timeout
    write_timeout: "30s"  # write timeout

    
