server:
  host: ${HOST} # host to bind to
  port: ${PORT} # port to listen on
  challenge_difficulty: ${CHALLENGE_DIFFICULTY} # difficulty target for PoW
  mode: "quotes" # or "proxy"
  proxy:
    target: "http://example.com" # target URL for proxy mode
    timeout: "5s" # proxy timeout
  quotes:
    file: "config/quotes.yml" # quotes file path
  connection:
    read_timeout: "30s" # read timeout
    write_timeout: "30s" # write timeout
    rate_limit: 10 # rate limit in requests per second
    burst_limit: 20 # burst limit in requests per second
    max_connections: 100 # maximum number of concurrent connections
    worker_pool_size: 10 # size of the worker pool
    queue_size: 50 # size of the connection queue
    base_backoff: "100ms" # base backoff duration
    max_backoff: "5s" # maximum backoff duration

